services:
  data.onLoadLayersLoadDirectories:
    class: con4gis\DataBundle\Classes\Listener\LoadLayersListener
    tags:
      - { name: kernel.event_listener, event: maps.layers.load, method: onLoadLayersLoadDirectories, priority: 3004 }
    arguments:
      - "@con4gis.layer_service"
  data.onLoadLayersLoadTypes:
    class: con4gis\DataBundle\Classes\Listener\LoadLayersListener
    tags:
      - { name: kernel.event_listener, event: maps.layers.load, method: onLoadLayersLoadTypes, priority: 3003 }
    arguments:
      - "@con4gis.layer_service"
  data.onLoadLayersLoadElements:
    class: con4gis\DataBundle\Classes\Listener\LoadLayersListener
    tags:
      - { name: kernel.event_listener, event: maps.layers.load, method: onLoadLayersLoadElements, priority: 3001 }
    arguments:
      - "@con4gis.layer_service"
  data.onLoadLayersCreateMapStructures:
    class: con4gis\DataBundle\Classes\Listener\LoadLayersListener
    tags:
      - { name: kernel.event_listener, event: maps.layers.load, method: onLoadLayersCreateMapStructures, priority: 3000 }
    arguments:
      - "@con4gis.layer_service"
  data.onLoadFeatureFilterCreateTagFilter:
    class: con4gis\DataBundle\Classes\Listener\LoadFeatureFilterListener
    tags:
      - { name: kernel.event_listener, event: maps.filters.load, method: onLoadFeatureFilters, priority: 422 }
    arguments:
      - "@con4gis.filter_service"
  routing.onLoadRouteFeaturesGetFeatures:
    class: con4gis\DataBundle\Classes\Listener\LoadRouteFeaturesListener
    tags:
      - { name: kernel.event_listener, event: load.route.features, method: onLoadRouteFeaturesGetFeatures, priority: 1024 }
  routing.onLoadAreaFeaturesGetFeatures:
    class: con4gis\DataBundle\Classes\Listener\LoadAreaFeaturesListener
    tags:
      - { name: kernel.event_listener, event: load.area.features, method: onLoadAreaFeaturesGetFeatures, priority: 1024 }
    arguments:
      - "@con4gis.area_service"